name: Generate Documentation

on:
  pull_request:
    branches:
      - dev

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0

      - name: Install dependencies
        run: npm ci

      - name: Generate Documentation
        id: generate-docs
        run: |
          output=$(npm run generate-docs)
          echo "::set-output name=output::$output"

      - name: Comment on Pull Request
        run: |
          output=$GITHUB_EVENT_PATH
          COMMENT="Generated documentation:\n\`\`\`${output}\`\`\`"

          npx octokit rest -o $GITHUB_REPOSITORY -r $GITHUB_REPOSITORY issues/create-comment@v1 \
            --issue_number ${{ github.event.pull_request.number }} \
            --body "$COMMENT" \
            --token ${{ secrets.GITHUB_TOKEN }}
