name: Generate Documentation

on:
  pull_request:
    branches:
      - dev

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0

      - name: Install dependencies
        run: npm ci

      - name: Generate Documentation
        id: generate-docs
        run: |
          output=$(npm run generate-docs)
          echo "Generated documentation:"
          echo "$output"

      - name: Print Documentation Output
        run: |
          echo "Documentation output from previous step:"
          echo "${{ steps.generate-docs.outputs.output }}"
