name: Generate Documentation

on:
  pull_request:
    branches:
      - dev

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0

      - name: Install dependencies
        run: npm ci

      - name: Generate Documentation
        id: generate-docs
        run: |
          output=$(npm run generate-docs)
          echo "::set-output name=output::$output"

      - name: Comment on Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = process.env['OUTPUT'];
            
            if (github && github.issues && github.issues.createComment) {
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `\`\`\`${output}\`\`\``
              });
            } else {
              console.error('Error accessing github context or createComment function.');
              console.log('github:', github);
            }
