name: Release on Dev PR

on:
  pull_request:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.8.1

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npx --node=20.8.1 semantic-release
